name: Test

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  rspec:
    name: Test on ruby ${{ matrix.ruby }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: prepare
    strategy:
      matrix:
        ruby: [ '2.6.x' ]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - run: brew install cmake pkg-config python3
      if: matrix.os == 'macos-latest'
    - run: pip3 install "pylint==2.4.4" " pylint-exit==1.1.0"
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Cache Ruby Gem
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake
